name: Deploy my Lambda

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: Set up installation
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.8
      - name: install librabries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt]; then pip install -r requirement.txt -t .; fi
      - name: Create zip bundle
        run: |
          cd function
          zip -r ../${{ github.sha}}.zip .
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
     
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.8
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Upload to s3
      run: aws s3 cp ${{ github.sha }}.zip s3://my-buck3t-123/${{ github.sha }}.zip
