name: Deploy my Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: Set up installation
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.8
      - name: install librabries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt]; then pip install -r requirement.txt -t .; fi
      - name: Create zip bundle
        run: |
          cd function
          zip -r ../${{ github.sha}}.zip .
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
        
      
